language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  else
    cargo test
  fi
